### ISSUE TITLE
无法处理消息

### ISSUE THREAD

**Issue by darriousliu** [mgsky1/FG#1]
处理消息函数handleGroupMsg(session)在整个项目里面没有调用过，chatA.txt和chaB.txt都是空的，删除后不能自动重新创建

**Comment by mgsky1** [comment]
只有在群里有发消息时，并且机器人要在群里，`handleGroupMsg(session)`方法才会被触发，然后`chatA.txt`或`chatB.txt`里才会有内容。不知道你那边有木有报错，如果有的话，可以贴上报错信息。然后那两个文件是在首次机器人扫描到配置文件中的新群后自动创建的，不要误删。

**Comment by darriousliu** [comment]
![7`$%9M4$SLC1 YYUFI7`7SN](https://user-images.githubusercontent.com/60057825/84795501-2ab76b00-b02a-11ea-802b-ab82244ed2a2.png)
发消息都可以发出去，就是接收不到消息

**Comment by darriousliu** [comment]
接收不到消息，然后文件就是空的

**Comment by mgsky1** [comment]
你可以先把定时器的触发时间设置的久一些，然后你往群里发消息，看一看控制台会不会有对应的消息打出来，正常的话，是有的，比如
`[2020-06-16 23:36:36,761 nonebot] INFO: Self: 123456 Message 25136 from 45678@[群:45678]: '我们又赢了'`

**Comment by darriousliu** [comment]
好像还是不行

**Comment by master-lzh** [comment]
ss

**Comment by darriousliu** [comment]
`handleGroupMsg(session)`这个函数一直没触发

**Comment by mgsky1** [comment]
你往群里发消息时，nonebot的控制台会有对应的消息输出吗？就像我上条评论中的示例一样。你之前说发消息都可以发出去，是说机器人可以往群里正常发送消息吗？------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;master-lzh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月17日(星期三) 凌晨0:03
收件人:&nbsp;&quot;mgsky1/FG&quot;<FG@noreply.github.com&gt;;
抄送:&nbsp;&quot;Martin Huang&quot;<563044462@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mgsky1/FG] 无法处理消息 (#1)

**Comment by darriousliu** [comment]
没输出，但是机器人可以发消息

**Comment by mgsky1** [comment]
你配置文件部分填写正确吗？有两个地方需要填写groupid，也就是群号。如果都正确，让我想想为什么会这样吧，我这边都没有出现过------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;master-lzh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月17日(星期三) 凌晨0:13
收件人:&nbsp;&quot;mgsky1/FG&quot;<FG@noreply.github.com&gt;;
抄送:&nbsp;&quot;Martin Huang&quot;<563044462@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mgsky1/FG] 无法处理消息 (#1)

**Comment by darriousliu** [comment]
两个位置都填了，然后端口号也没问题
![U$3T6VKD0O} }7%L131(IP0](https://user-images.githubusercontent.com/60057825/84800638-acaa9280-b030-11ea-842b-15807922f6ed.png)
![image](https://user-images.githubusercontent.com/60057825/84800804-e67b9900-b030-11ea-9c76-1c73896cfd3e.png)

**Comment by mgsky1** [comment]
方便贴一下你的运行环境吗？包括python版本，系统，酷Q版本之类的相关信息------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;master-lzh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月17日(星期三) 凌晨0:13
收件人:&nbsp;&quot;mgsky1/FG&quot;<FG@noreply.github.com&gt;;
抄送:&nbsp;&quot;Martin Huang&quot;<563044462@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [mgsky1/FG] 无法处理消息 (#1)

**Comment by darriousliu** [comment]
python3.7，win10 1903，
![image](https://user-images.githubusercontent.com/60057825/84801350-a36df580-b031-11ea-9818-c224bc870f6b.png)

**Comment by mgsky1** [comment]
不好意思，今天刚放假。确定我们的CQHTTP是一个版本？界面好像不太一样，我用的是[最新的版本](https://github.com/richardchien/coolq-http-api/releases)，即使我配置文件中没有添加群信息，机器人这边也是有反应的。
![]()
<img width="961" alt="QQ20200701-190340@2x" src="https://user-images.githubusercontent.com/23556693/86237222-f321f480-bbcd-11ea-87c0-c2cfd58514b2.png">

<img width="966" alt="QQ20200701-190700@2x" src="https://user-images.githubusercontent.com/23556693/86237273-0e8cff80-bbce-11ea-8a88-d6fe67032a48.png">



> 两个位置都填了，然后端口号也没问题
> ![U$3T6VKD0O} }7%L131(IP0](https://user-images.githubusercontent.com/60057825/84800638-acaa9280-b030-11ea-842b-15807922f6ed.png)
> ![image](https://user-images.githubusercontent.com/60057825/84800804-e67b9900-b030-11ea-9c76-1c73896cfd3e.png)

**Comment by darriousliu** [comment]
我现在可以了，看原因应该是当时那个配置文件没弄好，websocket的反向代理出了问题
过了这么久都还记得这个问题，十分感谢了

**Comment by mgsky1** [comment]
没事～
